name: build-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            apt-get -y --no-install-recommends install \
            build-essential \
            lsb-release \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            && echo "start" \
            && lsb_release -a
