name: build-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pguyot/arm-runner-action@v2.5.2
        id: build_image
        with:
          base_image: 'https://downloads.raspberrypi.org/raspios_full_arm64/images/raspios_full_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-full.img.xz'
          commands: |
            apt-get -y --no-install-recommends install \
            build-essential \
            lsb-release \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            && echo "start" \
            && lsb_release -a \
            && mkdir rpi-whispercpp \
            && cd rpi-whispercpp \
            && python3 -m venv .venv \
            && source .venv/bin/activate \
            && pip3 install whispercpp
